services:
  minecraft:
    container_name: itzgMinecraftServer
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "25575:25575/tcp"
    environment:
      TYPE: "FABRIC"
      VERSION: "VERSION"
      MODE: "survival"
      MEMORY: "2G"
      MOTD: "Minecraft Server VERSION"
      LEVEL_TYPE: "DEFAULT"
      EULA: "TRUE"
      ONLINE_MODE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
    restart: unless-stopped
    volumes:
      - ./data:/data